#!/bin/bash
path="$HOME/.config/bashquote/"

if [[ $1 == "" ]] then
    bashquote help
fi

if [[ $1 == "help" ]] then
    echo "bashquote help       : show help"
    echo "bashquote set <name> : select a quotes file"
    echo "bashquote list       : list all available quotes files"
    echo "note: you can add your quotes files with a .txt extension in ~/.config/bashquote/"
    echo "      each quote must be on a single line"
    echo "      the first line of the file is reserved for the symbol that will be used as a prefix and suffix"
fi

if [[ $1 == "list" ]] then
    for f in $(ls $path); do
        echo " - ${f%.*}"
    done
fi

if [[ $1 == "set" ]] then
    if [[ -f $path/$2.txt ]] then
        bashrc=$(grep -o -m 1 "bashquote" $HOME/.bashrc)
        if [[ "" == $bashrc ]] then
            echo "writing config in your .bashrc" 
            echo "# managed by bashquote" >> $HOME/.bashrc
            echo "QUOTEFILE=$2.txt" >> $HOME/.bashrc
            echo "SYMBOL=\$(head -n 1 \$HOME/.config/bashquote/\$QUOTEFILE)" >> $HOME/.bashrc
            echo "QUOTE=\$(tail -n+2 \$HOME/.config/bashquote/\$QUOTEFILE | shuf -n 1)" >> $HOME/.bashrc
            echo "COLUMNS=\$(tput cols)" >> $HOME/.bashrc
            echo "printf \"\n%*s\n\n\" \$(((\${#QUOTE}+\$COLUMNS)/2)) \"\$SYMBOL \$QUOTE \$SYMBOL\"" >> $HOME/.bashrc
        else 
            line=$(awk '/QUOTEFILE=/{ print NR; exit }' $HOME/.bashrc) 
            sed -iE "$line s/QUOTEFILE=\(.*\)/QUOTEFILE=$2.txt/g" $HOME/.bashrc
            echo "Quotes file has been changed."
        fi
    else
        echo "$2 is not a valid quotes file."
        echo "try \"bashquote list\" to see existing quotes file."
    fi
fi
